name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{secrets.GH_TOKEN}}

      - name: Determine release type
        run: echo "IS_PRERELEASE=$(if [ "$(echo $GITHUB_REF | sed -r 's/refs\/[a-zA-Z]+\/v[0-9]+\.[0-9]+\.[0-9]+//')" ]; then echo true; else echo false; fi)" >> $GITHUB_ENV

      - name: Generate release notes
        run: |
          mkdir ./tmp
          git log -1 --pretty=format:"%b" > ./tmp/release_notes

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./tmp/release_notes
          token: ${{secrets.GH_TOKEN}}
          prerelease: ${{env.IS_PRERELEASE == 'true'}}
